version: '3.8'

services:
  app:
    container_name: email-otp-app
    image: codecshivam/email-otp-auth:latest
    ports:
      - "3000:3000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - CLIENT_URL=${CLIENT_URL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: "no"